### ISSUE TITLE
Assets drained didnt trigger on Fries DAO Hack

### ISSUE THREAD

**Issue by christian-forta** [NethermindEth/forta-starter-kits#13]
https://etherscan.io/tx/0xa4fc1486c2266a51c1701d4fbeb2b2f0a5638b832e616fc1a86ca100d1e8679d

**Comment by Vxatz** [comment]
Thank you for bringing this up.

Closing the issue - It has been fixed in [PR#18](https://github.com/NethermindEth/forta-starter-kits/pull/18)
