### ISSUE TITLE
Detect high profits in EOA accounts that were not directly involved in a flashloan

### ISSUE THREAD

**Issue by kovart** [NethermindEth/forta-starter-kits#15]
Some attackers at the end of flashloan perform a transfer to a secondary EOA. This way they try to hide the profit of the attack from detection.

An example of such a transaction can be seen here: https://etherscan.io/tx/0x47c7ab4a9e829415322c8933cf17261cd666dbeb875f0d559ca2785d21cae661

It would be nice to add support for detecting such transactions.

**Comment by Vxatz** [comment]
Thank you for bringing this up!

Closing the issue - it has been in fixed in PRs #17 and #19
