### ISSUE TITLE
FP issue (USDT) - ice phishing bot 

### ISSUE THREAD

**Issue by Ivan1905** [NethermindEth/forta-starter-kits#44]
Hi Vasilis,

I have observed that the scam detector triggered many ice phishing alerts which I assessed like False positives. Apparently in many cases the bot is flagging addresses that seem to be stealing USDT but they are not.

Let me give you an example:

1. Forta alert here: https://explorer.forta.network/alert/0xeab4a1b5236c7de40fa4aba959e7c5ca59fa3f7fd734526ca30e1559618e89a8
Etherscan address here:
https://etherscan.io/address/0x08a34cac368f1206a30803787d5e00cf4265c347

As you can see in this example, "targets" seem to be approving the suspected address and then funds are being sent to 0x4baE69a92C1F812Cb2B74fcd2f3E664aEa435c46. What is very strange is that in most of the cases, targets are interacting in many opportunities with the mentioned address  which seems like something illogical. 

Attaching you some other examples here:

- https://explorer.forta.network/alert/0x5a3a9d5262bc90aa1d9c885085b8cb65d27f6b2747c550b77b03b35d80b078fd
- https://explorer.forta.network/alert/0xb84139dd54655a8750d6fc071a225e5ebffa420baec107cd36ee4c35e19b964b
- https://explorer.forta.network/alert/0xd1d6cfcb03c3db17a16f9e3e9aae027f02dade4e95edf3c33c324354e0ec0cdd

**Comment by Vxatz** [comment]
Hi @Ivan1905,

the issue that I notice here is that both the `ICE-PHISHING-HIGH-NUM-ERC20-APPROVALS` and `ICE-PHISHING-HIGH-NUM-APPROVED-TRANSFERS` couldn't catch the mentioned interactions, as at least in these examples, they happen after the `Approval`/1st `Transfer`.

**Comment by christian-forta** [comment]
i think this would be a good addition.

**Comment by christian-forta** [comment]
@Vxatz , do you have status on this one? Seems like its the source for a lot of FPs.

**Comment by christian-forta** [comment]
Sounds good. Let's see how that improves precision and we can revisit.

**Comment by Vxatz** [comment]
Checks added on https://github.com/NethermindEth/forta-starter-kits/pull/52
