### ISSUE TITLE
FP issue (contract creation bug) - ice phishing bot

### ISSUE THREAD

**Issue by Ivan1905** [NethermindEth/forta-starter-kits#45]
Hi Vasilis,

Let me share another set of FPs I have found. In this case, the scam detector bot seems to be flagging addresses that are creating token contracts, opening pools in uniswap, then adding and removing liquidity. It seems like rug pulls but the scam detector is identifying this as ice phishing.

1. Example1: 
Forta alert: https://explorer.forta.network/alert/0x228958ebd084fe1b60306ad673896118238ba8d76b8f37539319bc4ac3ca51cd
Etherscan link: https://etherscan.io/address/0xa1d600554f118a7a876dd2362cfe80d805959b8a

2 Example2:
Forta alert: https://explorer.forta.network/alert/0xcfafa4b4d8d020e70f6339f3a1070fd48756309e43bab5593448d4b7e534e0ab
Etherscan link: https://etherscan.io/address/0x6138916d226ffba30ac7e38a83f5448be326355a

3 Example3:
Forta alert: https://explorer.forta.network/alert/0xadb78dda5ee6588455c0cff9eec348b12152fe1561ca0d7c4671c0e23b9db1a5
etherscan link: https://etherscan.io/address/0xf3d54f2106c3ad43bbcbdc2a8d0dc4b4ae4471de

**Comment by Vxatz** [comment]
Hi Ivan,

this _Ice Phishing bot_ [alert](https://explorer.forta.network/alert/0xb59c77a19542d524172a3f2eac63842cbaea8febf1ced8270a3d79df0dfaf516) is fired when a contract (or its creator, as in this case) that was previously flagged as [suspicious](https://explorer.forta.network/alert/0x68f01657aa77604eb70305b157dd52818416d70c07ae0d20611e2a3e67dda998) by the _Malicious Smart Contract ML Bot_ is involved in a transfer, without checking for any thresholds (e.g. over 3 transfers)

We can possibly remove it if it results in FPs.

**Comment by christian-forta** [comment]
I suggest to remove it as we now have dedicated bots to cover scams related to contracts.
