### ISSUE TITLE
High drop rate in May for the asset-drained bot

### ISSUE THREAD

**Issue by manola69** [NethermindEth/forta-starter-kits#49]
Hi Vasilis, the asset-drained bot has some high drop rates in the month of may, in the BSC chain (though it only has one node assigned). Would appreciate you taking a look at it, and conisdering sharding. Thank you!

**Comment by Vxatz** [comment]
Hi @manola69, does this concern all of May? Because at around May 20, we upgraded the bot and enabled sharding. (Asking also because checking the bot health page, I'm seeing only specific nodes performing poorly)
