### ISSUE TITLE
FP mitigation for ice phishing bot

### ISSUE THREAD

**Issue by christian-forta** [NethermindEth/forta-starter-kits#51]
Seems like this address is being reported as a known scammer, but the metadata contains no info on what label was observed. Cant really find info on this address being flagged as a known scammer. 

https://explorer.forta.network/alert/0x8b95fe9bf2c444fccee06ccf0207e0234ffe8da78799560c875179522d938ca6

**Comment by Vxatz** [comment]
@christian-forta, this specific alert uses the scam sniffer db (https://github.com/scamsniffer/scam-database/blob/59e6095b990cce26e53b7afebf4811e9873449c3/blacklist/address.json#L1205). Should we take any actions?

**Comment by christian-forta** [comment]
Could you just add attribution to the alert, so it's clear where the data
is coming from? Will help troubleshooting and getting FPs addressed.

**Comment by Vxatz** [comment]
@christian-forta, changed the Finding name on these alerts to mention that it's coming from ScamSniffer.
