### ISSUE TITLE
FP on asset drained

### ISSUE THREAD

**Issue by christian-forta** [NethermindEth/forta-starter-kits#56]
https://explorer.forta.network/alert/0x4047f42cbc70f8cc1b8563151f13be43950ee13f09de9afe76f34a5388d3695d claims that the DAI balance of 0xbEbc was drained by 99%. 

Reviewing the tx https://explorer.phalcon.xyz/tx/eth/0x4ebdb03264fe8b2837b5ce01d01c117372e75107b94c330887b63c8e62513285

shows that the DAI balance changed only from: 153025311025020457056586169 to 152960724868721505903986058

**Comment by Vxatz** [comment]
Fixed on https://github.com/NethermindEth/forta-starter-kits/pull/57.
