### ISSUE TITLE
FP on large profit bot (blur withdrawl)

### ISSUE THREAD

**Issue by christian-forta** [NethermindEth/forta-starter-kits#59]
https://explorer.forta.network/alert/0xeeba00288acb48a6fa9427b25060ee25faa21249acabfce136853b8d1ccdaa6a

Can we somehow mitigate these classes of FPs? Maybe if the logs are very short, like in this case?

**Comment by Vxatz** [comment]
Fixed on https://github.com/NethermindEth/Forta-Agents/pull/406.
