### ISSUE TITLE
FP on ICE-PHISHING-PIG-BUTCHERING

### ISSUE THREAD

**Issue by christian-forta** [NethermindEth/forta-starter-kits#65]
https://explorer.forta.network/alert/0xc1554a62beb0253bc6ae158aa2e42ef2f2a5c584bfc4c0202c5c66c8290b57b2
https://etherscan.io/tx/0x7f12255758626c5978cd4f9adbedc825d33ed19cac52c3f87db0dd64849cd771

**Comment by Vxatz** [comment]
@christian-forta, the bot checks if the etherscan tag exists using the Forta API. It seems that in this case, the call failed (although a retry mechanism is also in place).

However, I've seen two more FPs, for [cex.io](https://etherscan.io/address/0xc9f5296Eb3ac266c94568D790b6e91ebA7D76a11) and [KuCoin 11](https://etherscan.io/address/0xeC30d02f10353f8EFC9601371f56e808751f396F) for which the API doesn't return the etherscan tag.

To address this, I added a nonce check for the "attacker" (has to be < 50000) to mitigate the issue.
